<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219024714 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, telefone_celular VARCHAR(20) DEFAULT NULL, telefone_fixo VARCHAR(20) DEFAULT NULL, cep VARCHAR(10) NOT NULL, endereco VARCHAR(255) NOT NULL, cidade VARCHAR(100) NOT NULL, estado VARCHAR(2) NOT NULL, complemento VARCHAR(100) DEFAULT NULL, criado_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tipo VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cliente_pf (cpf VARCHAR(14) NOT NULL, rg VARCHAR(20) NOT NULL, rg_orgao_expedidor VARCHAR(100) NOT NULL, rg_data_emissao DATE NOT NULL, data_nascimento DATE NOT NULL, nome_completo VARCHAR(50) NOT NULL, estado_civil VARCHAR(50) DEFAULT NULL, profissao VARCHAR(100) DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cliente_pj (cnpj VARCHAR(14) NOT NULL, razao_social VARCHAR(255) NOT NULL, nome_fantasia VARCHAR(255) DEFAULT NULL, inscricao_estadual VARCHAR(20) DEFAULT NULL, inscricao_municipal VARCHAR(20) DEFAULT NULL, enderec_sede VARCHAR(255) NOT NULL, representante_legal VARCHAR(255) NOT NULL, representante_cpf VARCHAR(14) NOT NULL, representante_rg VARCHAR(20) NOT NULL, representante_cargo VARCHAR(100) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE cliente_pf ADD CONSTRAINT FK_AB7D8665BF396750 FOREIGN KEY (id) REFERENCES cliente (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cliente_pj ADD CONSTRAINT FK_A2CBCA4EBF396750 FOREIGN KEY (id) REFERENCES cliente (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cliente_pf DROP CONSTRAINT FK_AB7D8665BF396750');
        $this->addSql('ALTER TABLE cliente_pj DROP CONSTRAINT FK_A2CBCA4EBF396750');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE cliente_pf');
        $this->addSql('DROP TABLE cliente_pj');
    }
}
