<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260218213217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pre_cadastro (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome_cliente VARCHAR(255) NOT NULL, cpf VARCHAR(14) NOT NULL, tipo VARCHAR(50) NOT NULL, telefone VARCHAR(20) DEFAULT NULL, area_direito VARCHAR(255) NOT NULL, tem_prazo BOOLEAN NOT NULL, natureza VARCHAR(20) NOT NULL, fase_judicial VARCHAR(50) DEFAULT NULL, numero_processo VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE pre_cadastro');
    }
}
